リスト表示されるArtの表示カード
ih14c-13-14/artist-frontend pull request #103
Opened 2023-07-04 06:09 UTC by aogumobc

# やったこと
「さがす」タブでArtが表示されるときのカード

# やらないこと

# レビュー前チェックシート(全てチェックしてからレビュー依頼)

- [x] セルフレビューをした
- [x] 手元でテストが通った
  - [x] `yarn lint`
  - [ ] `yarn test`
  - [x] `yarn build`

yarn test って `14 passed` が正常なんですか？
一応試したけどチェックつけてないです

2023-07-04 06:11 UTC, na2na-p commented
> yarn test って 14 passed が正常なんですか？

落ちてなければ大丈夫です

2023-07-04 06:11 UTC, na2na-p approved these changes

2023-07-04 06:11 UTC, na2na-p commented on src/components/Layout/ArtCard/ArtCard.component.tsx
> +import React from 'react';
```suggestion
```

現代のReactだと不要です（修正は不要

2023-07-04 06:11 UTC, na2na-p commented on src/components/Layout/ArtCard/ArtCard.stories.tsx
> +      imageSrc="" // ここどうすればいいんですか？
いったんこのままでいいです

2023-07-04 06:30 UTC, na2na-p requested changes

2023-07-04 06:30 UTC, na2na-p commented on src/components/Layout/ArtCard/ArtCard.component.tsx
> +      // marginBottom 入れないと複数表示したときに互いにぴったりくっついてしまう
複数表示したときの見た目を制御するのはこのレイヤーの責務ではありません。利用側でflex gapを用いて制御すべきです

2023-07-05 00:42 UTC, aogumobc commented on src/components/Layout/ArtCard/ArtCard.component.tsx
> +import React from 'react';
わかりました

2023-07-05 00:50 UTC, aogumobc commented on src/components/Layout/ArtCard/ArtCard.stories.tsx
> +    <>
`<StackChidren gap={}>` にしました

2023-07-05 01:16 UTC, aogumobc commented
@na2na-p 
`git rebase origin/main` しました

2023-07-11 10:06 UTC, na2na-p commented
フルリメイクするのでclose

2023-07-11 10:06 UTC, closed without merging