郵便番号と住所をアイコン付きに整形するコンポネント
ih14c-13-14/artist-frontend pull request #107
Opened 2023-07-05 01:49 UTC by aogumobc

# やったこと
7桁の郵便番号と住所をアイコン付きに整形

# やらないこと
`isTruncated` がうまく動かなかった (そもそもここじゃない？)

# レビュー前チェックシート(全てチェックしてからレビュー依頼)

- [x] セルフレビューをした
- [x] 手元でテストが通った
  - [x] `yarn lint`
  - [x] `yarn test`
  - [x] `yarn build`

2023-07-05 02:07 UTC, na2na-p requested changes

2023-07-05 02:07 UTC, na2na-p commented on src/components/commons/Styling/PostCode/PostCode.component.tsx
> +  const fixedPostCode = `${firstPart}-${secondPart}`;
```suggestion
  // 郵便番号の整形
  const fixedPostCode = useMemo(() => {
    const postCodeString = postCode.toString();
    const firstPart = postCodeString.slice(0, 3);
    const secondPart = postCodeString.slice(3, 7);
    return `${firstPart}-${secondPart}`;
  }, [postCode]);
```

2023-07-05 02:07 UTC, na2na-p commented on src/components/commons/Styling/PostCode/PostCode.component.tsx
> +    <div style={{ display: 'flex', maxWidth: '100px' }}>
ほんとうに？

<img width="435" alt="image" src="https://github.com/ih14c-13-14/artist-frontend/assets/49822810/10d83519-2622-41e8-959c-c31c5ae8c779">

2023-07-05 02:07 UTC, na2na-p commented on src/components/commons/Styling/PostCode/PostCode.component.tsx
> +import { StackChildren } from '../StackChildren/StackChildren';
```suggestion
import { Stack } from '@/features/ui/Stack';
```

2023-07-05 02:07 UTC, na2na-p commented on src/components/commons/Styling/PostCode/PostCode.component.tsx
> +    </div>
Stack使ってるならflex指定不要では？
また、sxProp潰れてて不便なので新設したStack利用してください

```suggestion
    <Stack flexDirection="row" sx={{ maxWidth: '100px' }}>
      <LocationOn sx={{ marginRight: '5px' }} />
      <Typography isTruncated>
        〒 {fixedPostCode} {address}
      </Typography>
    </Stack>
```

2023-07-05 02:07 UTC, na2na-p commented on src/components/commons/Styling/PostCode/PostCode.component.tsx
MaxWidth超えてるので効いてないです、構造が悪さしてる。修正案含めて下記suggestionで記載済み
<img width="494" alt="image" src="https://github.com/ih14c-13-14/artist-frontend/assets/49822810/b1ee2cdd-68e8-4fb1-95a7-629ce90e3a0d">

2023-07-07 02:20 UTC, na2na-p commented on src/components/commons/Styling/PostCode/PostCode.component.tsx
> +    <ThemeProvider theme={theme}>
コンポーネント内部でProvider呼ばれていて泣いています

2023-07-07 02:45 UTC, aogumobc commented
![Desktop Screenshot 2023 07 07 - 11 40 59 27](https://github.com/ih14c-13-14/artist-frontend/assets/106609996/69ac93e3-2dd1-40e7-b6f8-3172308ed5bb)

2023-07-07 02:49 UTC, na2na-p requested changes
Lint落ちてます

2023-07-07 02:49 UTC, na2na-p commented on src/components/commons/Styling/PostCode/PostCode.component.tsx
> +  };
```suggestion
  } satisfies SxProps<Theme>;
```

修正は任意です、つけるなら統一しよう

2023-07-07 02:50 UTC, aogumobc commented on src/components/commons/Styling/PostCode/PostCode.component.tsx
> +  };
します

2023-07-07 02:59 UTC, aogumobc commented on src/components/commons/Styling/PostCode/PostCode.component.tsx
> +    <ThemeProvider theme={theme}>
sxにしました

2023-07-07 03:23 UTC, na2na-p approved these changes
多分ヨシ！

2023-07-07 03:23 UTC, merged