ページのパス追加
ih14c-13-14/artist-frontend pull request #12
Opened 2023-06-08 07:15 UTC by aogumobc

# やったこと
RouterConfigでパスの設定

# やらないこと

2023-06-08 07:18 UTC, na2na-p requested changes
`yarn lint --fix`してからもう一度お願いします！

2023-06-08 07:21 UTC, aogumobc commented
やりましたおねがいします

2023-06-08 07:36 UTC, na2na-p requested changes
- (提案) RouterConfigを設置するかどうか
- (提案) エラーハンドリング方針検討
- (指摘) typo
- (指摘) パス切り出し
- (指摘) kebab-case

各画面のパスや命名については見ていません。該当画面実装時に確認する(あるいは確認してください)

2023-06-08 07:36 UTC, na2na-p commented on src/App.tsx
> +  return <RouterConfig />;
修正は任意です)
RouterConfigの中身そのままここに配置していいと思います。

2023-06-08 07:36 UTC, na2na-p commented on src/pages/NotFound.tsx
> +export const NotFound: React.FC = () => {
こちらも修正は任意です、というか今後の方針にも絡むので慎重に
エラーハンドリングとしてレイヤーを設けて、そこで出しわけをする、というのはどうでしょうか。
例えばフェッチけどバックエンドからはリソースがありませんと言われた、であるとか誤ったURLを踏んだのか、であるとか、クエリ飛ばしたけど引数おかしくて弾かれた、とか。

参考: 
https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary
みたいなものを使って配下のコンポーネントから送出された例外を捕まえて云々といった処理ができるようになります。

2023-06-08 07:36 UTC, na2na-p commented on src/routing/RouterConfig.tsx
> +import { SignupCofirm } from '@/pages/SignupConfirm';
```suggestion
import { SignupConfirm } from '@/pages/SignupConfirm';
```

2023-06-08 07:36 UTC, na2na-p commented on src/routing/RouterConfig.tsx
> +          <Route path="/passwordchanged" element={<PasswordChanged />} />
pathがたくさん入っているオブジェクトを取得する関数(例えば`getRoutes`)を作り、そこから取るようにしましょう。
例えば、画面レイヤーでパス指定して移動したい時にハードコードせずに済むようになります。
型安全に作るのは結構めんどくさいので簡易的なもので構わないです。

```ts
getRoutes = () => {
  return {
    showMap: {
      path: 'show-map',
    },
  }
}
```

```ts
const routes = getRoutes();
```
みたいな感じです

2023-06-08 07:36 UTC, na2na-p commented on src/routing/RouterConfig.tsx
> +          <Route path="/passwordchanged" element={<PasswordChanged />} />
また、パスはkebab-caseでセットしましょう

参考: https://off.tokyo/blog/kebab-case-url/

2023-06-08 07:40 UTC, na2na-p commented on src/pages/NotFound.tsx
> +export const NotFound: React.FC = () => {
404ひとつとっても
> 例えばフェッチけどバックエンドからはリソースがありませんと言われた、であるとか誤ったURLを踏んだのか

などと複数パターン存在します

2023-06-08 12:28 UTC, na2na-p requested changes
追加1点

2023-06-08 12:28 UTC, na2na-p commented on src/App.tsx
> +import { Footer } from './footer/Footer';
最低限ビルド通るようにしましょう、、、

<img width="977" alt="image" src="https://github.com/ih14c-13-14/artist-frontend/assets/49822810/6bd5a3dc-4657-42c0-b260-7095fc656720">

```suggestion
```

2023-06-09 01:17 UTC, aogumobc commented on src/App.tsx
> +  return <RouterConfig />;
このままでいきます

2023-06-09 01:18 UTC, aogumobc commented on src/pages/NotFound.tsx
> +export const NotFound: React.FC = () => {
フロントエンド班の進捗を見ながら優先度低めで設定しておきます。

2023-06-09 01:18 UTC, aogumobc commented on src/routing/RouterConfig.tsx
> +import { SignupCofirm } from '@/pages/SignupConfirm';
fixed

2023-06-09 02:53 UTC, aogumobc commented on src/routing/RouterConfig.tsx
> +          <Route path="/passwordchanged" element={<PasswordChanged />} />
`as const satisfies` で定数の export をします。

2023-06-09 02:53 UTC, aogumobc commented on src/App.tsx
> +import { Footer } from './footer/Footer';
該当の import 文を消去しました。

2023-06-09 02:53 UTC, aogumobc commented
@na2na-p 修正終わったのでレビューお願いします

2023-06-09 02:59 UTC, na2na-p requested changes
数点

2023-06-09 02:59 UTC, na2na-p commented on src/routing/RouterConfig.tsx
> +    <>
Fragmentは不要です

2023-06-09 02:59 UTC, na2na-p commented on src/routing/RouterConfig.tsx
> +export const RouterConfig: React.FC = () => {
修正は任意です

別にFC書かなくていいです

2023-06-09 02:59 UTC, na2na-p commented on src/routing/RouterConfig.tsx
> +import React from 'react';
```suggestion
import type { FC } from 'react';
```


参考: https://qiita.com/Yz_4230/items/ce70927d36f7a6cf619d

2023-06-09 03:03 UTC, aogumobc commented on src/routing/RouterConfig.tsx
> +    <>
`<BrowserRouter>` しかなかったので `<></>` を消しました

2023-06-09 03:03 UTC, aogumobc commented on src/routing/RouterConfig.tsx
> +export const RouterConfig: React.FC = () => {
消しました

2023-06-09 03:04 UTC, aogumobc commented
記述の軽微な修正

2023-06-09 03:21 UTC, na2na-p approved these changes
LGTM! お疲れ様でした

2023-06-09 03:21 UTC, merged