ハンバーガーメニュー作成
ih14c-13-14/artist-frontend pull request #166
Opened 2023-07-11 04:47 UTC by N55039

# やったこと
ハンバーガーメニュー作成(Onclickまで)

# やらないこと

# 動作確認

# レビュー前チェックシート(全てチェックしてからレビュー依頼)

- [x] セルフレビューをした
- [x] 手元でテストが通った
  - [x] `yarn lint`
  - [x] `yarn test`
  - [x] `yarn build`

2023-07-11 05:17 UTC, aogumobc commented on src/components/commons/Menubar/Menubar.type.ts
> +  label: string;
`label` 使われてる形跡が見当たらないんですけどどこかで使いますか？ or 使ってますか？

2023-07-11 05:17 UTC, aogumobc commented on src/components/commons/Menubar/Menubar.component.tsx
> +import React, { useState } from 'react';
`import React` なくても大丈夫です (修正不要)

2023-07-11 05:17 UTC, aogumobc commented on src/components/commons/Menubar/Menubar.component.tsx
> +import DehazeIcon from '@mui/icons-material/Dehaze';
src/components/commons/Menubar/Menubar.stories.tsx では
`import { Close, Dehaze } from '@mui/icons-material';`
となっていますね。統一させたほうがいいでしょう。

2023-07-11 05:17 UTC, aogumobc commented on src/components/commons/Menubar/Menubar.stories.tsx
> +};
src/components/commons/Menubar/Menubar.component.tsx
15行目で `useState` を使っているので、クリックされるまでどちらも `CloseIcon` になってます。

2023-07-11 05:50 UTC, N55039 commented on src/components/commons/Menubar/Menubar.type.ts
> +  label: string;
使っていないです。

2023-07-11 05:59 UTC, na2na-p commented
そのany waningは多分最新main取り込んだら消えるはず
#153 でなおしました

2023-07-11 10:50 UTC, aogumobc commented on src/components/commons/Menubar/Menubar.type.ts
> +  icon: OverridableComponent<SvgIconTypeMap>;
そもそも論になって申し訳ないんですけど引数に `icon` って必要ですかね？
いつ開いても `三` になっていて `X` になっていないのであれば不要だと思います。

2023-07-11 10:52 UTC, aogumobc commented on src/components/commons/Menubar/Menubar.type.ts
> +  label: string;
figmaを見るとアイコンの下に「メニュー」とあるので、使うのが正でしょう。
`src/components/commons/Menubar/Menubar.component.tsx` と `src/components/commons/Menubar/Menubar.stories.tsx` の修正をお願いします。

2023-07-11 10:53 UTC, aogumobc commented on src/components/commons/Menubar/Menubar.stories.tsx
> +};
同様に、引数に `icon` を与える必要がありません。
`label` を与えることになると想定されます。

2023-07-12 00:47 UTC, N55039 commented on src/components/commons/Menubar/Menubar.stories.tsx
> +};
labelは今後反映します。

2023-07-12 02:16 UTC, aogumobc commented on src/components/commons/Menubar/Menubar.type.ts
> +  onClick: React.MouseEventHandler<HTMLButtonElement> | undefined;
「複数の場面でこのコンポネントが呼び出され、onClick の内容に差分が出る」でなければ引数に onClick を用意する必要がないですね (component.tsx 内に `handleClick` もありますし)

2023-07-12 02:16 UTC, aogumobc commented on src/components/commons/Menubar/Menubar.stories.tsx
> +  // label: 'メニュー'を渡す,
`label` を用意するのは呼び出し先で差分があることが想定されるからなので、ここも必要ないと思います。
`component.tsx` 内で label の記述をしましょう。

2023-07-12 02:16 UTC, aogumobc commented on src/components/commons/Menubar/Menubar.component.tsx
> +    </MuiButton>
label を表示するとしたらここですね。
コメントアウトで構わないのでその旨を記述しておいてください。

2023-07-12 03:02 UTC, aogumobc commented
コミットされてないです！！

2023-07-13 06:07 UTC, na2na-p requested changes
数が多いですがおねがいします。

作業前に`git reset --hard origin/header`としておいてください

2023-07-13 06:07 UTC, na2na-p commented on src/components/commons/Menubar/Menubar.component.tsx
> +  ...rest
外部から操作可能にすべきでないpropsも含まれていませんか？
例えばHeaderで使うだけのButtonなのにvariantの変更って本当にしたい？とか、本当にdisabledになるユースケースって存在するの...?とか。
また、`...rest`としている中に星の数ほどたくさんのpropsが入っているのですが、これらは本当に必要なのでしょうか？
![image](https://github.com/ih14c-13-14/artist-frontend/assets/49822810/3fdfb990-2331-4b19-8d65-77f213414e74)

汎用のコンポーネントならまだしも、Headerで使う！と目的がより明確なので、必要なもの最小限だけど外部へのインターフェースとして公開するようにしましょう。

2023-07-13 06:07 UTC, na2na-p commented on src/components/commons/Menubar/Menubar.component.tsx
> +  const [isClicked, setIsClicked] = useState(false);
開閉状態のstateってただのボタンが持つのではなく、(今後利用するはずの)Headerで管理すべきなのではないでしょうか？開閉状態をpropsで受け取って表示するのがよさそうに見えます

2023-07-13 06:07 UTC, na2na-p commented on src/components/commons/Menubar/Menubar.component.tsx
> +    </MuiButton>
レビュワーとしてもちゃんとsuggestion書けると意図が伝わりやすくていいですよ

![image](https://github.com/ih14c-13-14/artist-frontend/assets/49822810/93cf4daa-97b2-4b1d-87ec-a4852b7e9854)

2023-07-13 06:07 UTC, na2na-p commented on src/components/commons/Menubar/Menubar.component.tsx
> +  };
もしこのレイヤーでonClickHandler定義するならこうかも
```suggestion
  const handleClick = useCallback((event: React.MouseEvent<HTMLButtonElement>) => {
    setIsClicked(!isClicked);
    onClick?.(event);
  }, [isClicked, onClick]):
```

2023-07-13 06:07 UTC, na2na-p commented on src/components/commons/Menubar/Menubar.component.tsx
> +    setIsClicked(!isClicked);
>開閉状態のstateってただのボタンが持つのではなく、(今後利用するはずの)Headerで管理すべきなのではないでしょうか？開閉状態をpropsで受け取って表示するのがよさそうに見えます

これの結果として、
開閉状態の状態の更新関数も、結果としてpropとして渡されてくるonClickの中に入ってくるはずです

2023-07-13 06:07 UTC, na2na-p commented on src/components/commons/Menubar/Menubar.component.tsx
> +  const [isClicked, setIsClicked] = useState(false);
>開閉状態のstateってただのボタンが持つのではなく、(今後利用するはずの)Headerで管理すべきなのではないでしょうか？

これ、開閉状態でメニュー出す出さないが変わってきそう、というものがあります。
今後どうやって作るかによってはまた変わってきますが、現状の実装くみ取るとこういう解釈になります。

2023-07-18 21:17 UTC, closed without merging