NormalButton の追加
ih14c-13-14/artist-frontend pull request #23
Opened 2023-06-14 03:05 UTC by aogumobc

# やったこと
主にサインアップ画面で用いられる、決定や確認などの「アイコンを持たないボタン」の作成。

# やらないこと
具体的な width/ height の指定がまだないので `sx` は空欄

# レビュー前チェックシート(全てチェックしてからレビュー依頼)

- [x] セルフレビューをした
- [x] 手元でテストが通った
  - [x] `yarn lint`
  - [x] `yarn test`
  - [x] `yarn build`

2023-06-14 03:10 UTC, na2na-p requested changes
1点だけ

2023-06-14 03:10 UTC, na2na-p commented on src/components/form/inputs/NormalButton/NormalButton.stories.tsx
> +};
各variant(3種)で作りましょうか

2023-06-14 03:30 UTC, na2na-p requested changes
すみません、漏れてたのでもう一点お願いします

2023-06-14 03:30 UTC, na2na-p commented on src/components/form/inputs/NormalButton/NormalButton.stories.tsx
> +};
先のレビューで漏れたんですが、各argsの中に`disabled: false`と入れておきましょうか

```suggestion
  disabled: false;
};
```

2023-06-14 03:31 UTC, na2na-p commented on src/components/form/inputs/NormalButton/NormalButton.stories.tsx
> +};
<img width="448" alt="image" src="https://github.com/ih14c-13-14/artist-frontend/assets/49822810/c422d0d3-78a3-4536-b5f1-9e55789e0028">
こういうトグルが生えてきます

2023-06-14 03:35 UTC, na2na-p commented
すごいどうでもいいけどyarn testどう考えても通過してなさそうなのにチェックついててウケてます(PRとしては無問題だけど

2023-06-15 06:37 UTC, aogumobc commented on src/components/form/inputs/NormalButton/NormalButton.stories.tsx
> +};
追加したので `Controls` の項目に `disable` のトグルスイッチが出てきたはず

2023-06-15 06:39 UTC, aogumobc commented
ちなみに `yarn test` やると `No test files found` って出ます
一応テストやってみて動作してたからチェックつけちゃった

> すごいどうでもいいけどyarn testどう考えても通過してなさそうなのにチェックついててウケてます(PRとしては無問題だけど

2023-06-15 06:40 UTC, na2na-p commented
動作してた（未通過）🤔

2023-06-15 06:45 UTC, na2na-p approved these changes

2023-06-15 06:45 UTC, na2na-p commented on src/components/form/inputs/NormalButton/NormalButton.component.tsx
> +  disabled,
変更不要

1. ここ露出させずにrestの中に入ったままでよかったかも
2. 残すならdisabled=falseとしておくのがいいかも

2023-06-15 06:45 UTC, merged