検証用入力フィールド
ih14c-13-14/artist-frontend pull request #31
Opened 2023-06-15 08:19 UTC by aogumobc

# やったこと
検証用の `InputTextField` 作成。

# やらないこと

# レビュー前チェックシート(全てチェックしてからレビュー依頼)

- [x] セルフレビューをした
- [ ] 手元でテストが通った
  - [ x] `yarn lint`
  - [ ] `yarn test`
  - [ x] `yarn build`

2023-06-15 08:24 UTC, na2na-p requested changes
伝え方が悪くてすみません。
通常のTextFieldでいいです

2023-06-15 08:24 UTC, na2na-p commented on src/components/form/inputs/VerificationTextField/VerificationTextField.component.tsx
> +  const [val, setVal] = React.useState('');
状態管理は必要ないです。

プレーンな入力コンポーネントがやって欲しくないです。
もしやるとしたら利用側がvalueとonChangeインターフェースで扱うか、React-hook-formで管理します。

2023-06-15 08:24 UTC, na2na-p commented on src/components/form/inputs/VerificationTextField/VerificationTextField.stories.tsx
> +  variant: 'outlined',
disabled入れましょうか

2023-06-15 08:24 UTC, na2na-p commented on src/components/form/inputs/VerificationTextField/VerificationTextField.component.tsx
> +export const VerificationTextField = ({
合わせて型名等も修正お願いします

```suggestion
export const TextField = ({
```

2023-06-16 01:26 UTC, aogumobc commented on src/components/form/inputs/VerificationTextField/VerificationTextField.stories.tsx
> +  variant: 'outlined',
おけです

2023-06-16 01:26 UTC, aogumobc commented on src/components/form/inputs/VerificationTextField/VerificationTextField.component.tsx
> +export const VerificationTextField = ({
変更しました

2023-06-16 01:32 UTC, na2na-p approved these changes
多分動く、ヨシ

2023-06-16 01:55 UTC, merged